#!/bin/bash

# http://stackoverflow.com/a/3355423
cd "${0%/*}"

function createConfig {
	cp -nv conf/radio.default.toml conf/radio.toml
}

echo "Installing dependencies and building Parasprite Radio..."

createConfig

echo "Installing nodejs dependencies..."
npm install --no-optional

echo "Building app for development"
gulp

echo "Done! Now edit config.json, setup Icecast, MySQL, MPD etc."
echo "Start server with ./radio -d (or remove the -d for running in production)"
echo "Then open http://localhost:8002 in your web browser."
