#!/usr/bin/env node

process.argv.splice(2, 0, __dirname + "/server/cluster.coffee");

process.env.NODE_ENV = "production";

require(__dirname + '/node_modules/coffee-script/lib/coffee-script/command').run();
